name: thesis_loresdiz

channels:
  - defaults

dependencies:
  - pip
  - jupyterlab
  - python=3.9
  - numpy
  - matplotlib
  - pre-commit
  - scipy
  - pyyaml
  - pandas
  - networkx
  - plotly
  - pip:
    - kaleido
    - econpizza==0.6.1
